# Generated by Django 3.2.19 on 2023-11-10 14:56

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('edx_badges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgestatus',
            name='credly_qualification_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='badgestatus',
            name='state',
            field=django_fsm.FSMField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('revoked', 'Revoked'), ('replaced', 'Replaced')], default='pending', max_length=50),
        ),
    ]
